// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parauan_Andreea_Raluca_Proiect_MPD.Data;

#nullable disable

namespace Parauan_Andreea_Raluca_Proiect_MPD.Migrations
{
    [DbContext(typeof(Parauan_Andreea_Raluca_Proiect_MPDContext))]
    [Migration("20240113114952_Data_publicarii_ghidului")]
    partial class Data_publicarii_ghidului
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Parauan_Andreea_Raluca_Proiect_MPD.Models.Proiect_MPD", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Cod_apel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data_publicarii_ghidului")
                        .HasColumnType("datetime2");

                    b.Property<string>("Regiunea_de_dezvoltare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip_apel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Proiect_MPD");
                });
#pragma warning restore 612, 618
        }
    }
}
